on: push

permissions:
  contents: write

jobs:
  build:
    name: 部署到 GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - name: 指定node版本
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'

    - name: 拉取仓库代码
      uses: actions/checkout@v4

    - name: 安装task-get-pets依赖
      run: cd ./task-get-pets && npm install
    
    - name: 打包并执行脚本输出精灵数据文件
      run: |
        cd ./task-get-pets
        npm run build
        node ./dist/index.js
    
    - name: 将输出文件复制到前端目录中
      run: |
        cd ./task-get-pets
        cp ./dist/static/pets.json ../seer-pets-website/src/assets/pets.json

    - name: 配置 Git 用户信息
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .  # 添加文件到暂存区
        git commit -m "Automated commit: Copy file to repository"  # 提交更改
        git push origin dev  # 推送更改到仓库（注意这里是dev分支）
